#!/usr/bin/env bash
# install-bd-git-guard.sh — make it impossible for bd to mutate git.
#
# Installs a `bd` wrapper earlier on PATH than the real bd. The wrapper runs
# the real bd with scripts/git-guard/ prepended to PATH, so every git call bd
# makes hits a read-only shim. Agents keep typing `bd` exactly as before.
#
# Idempotent. Safe to re-run.

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
GUARD_DIR="$REPO_ROOT/scripts/git-guard"

# Locate the real bd, ignoring any wrapper we previously installed.
REAL_BD=""
while IFS= read -r candidate; do
  grep -q "bd-git-guard-wrapper" "$candidate" 2>/dev/null && continue
  REAL_BD="$candidate"; break
done < <(type -aP bd 2>/dev/null || true)

if [ -z "$REAL_BD" ]; then
  echo "install-bd-git-guard: bd not found on PATH; run scripts/setup.sh first" >&2
  exit 1
fi

# Choose a wrapper location that PATH reaches BEFORE the real bd.
WRAPPER_DIR=""
IFS=':' read -ra _parts <<< "$PATH"
for d in "${_parts[@]}"; do
  [ -z "$d" ] && continue
  if [ "$d" = "$(dirname "$REAL_BD")" ]; then break; fi
  if [ -d "$d" ] && [ -w "$d" ]; then WRAPPER_DIR="$d"; break; fi
done

if [ -z "$WRAPPER_DIR" ]; then
  echo "install-bd-git-guard: no writable PATH dir ahead of $REAL_BD" >&2
  echo "  Add one (e.g. ~/bin) to the front of PATH and re-run." >&2
  exit 1
fi

cat > "$WRAPPER_DIR/bd" <<WRAPPER
#!/usr/bin/env bash
# bd-git-guard-wrapper — generated by scripts/install-bd-git-guard.sh
# Runs bd with a read-only git shim ahead of the real git on PATH.
exec env PATH="$GUARD_DIR:\$PATH" "$REAL_BD" "\$@"
WRAPPER
chmod +x "$WRAPPER_DIR/bd"

echo "install-bd-git-guard: wrapper -> $WRAPPER_DIR/bd"
echo "install-bd-git-guard: real bd -> $REAL_BD"
echo "install-bd-git-guard: git shim -> $GUARD_DIR/git"
